### ISSUE TITLE
Fix build console warnings

### ISSUE THREAD

**Issue by shashwatbangar** [hotwax/receiving#102]
```
warning: 'emitter' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/order/actions.ts:8:8:
    6 | import { hasError, showToast } from '@/utils'
    7 | import { translate } from '@/i18n'
 >  8 | import emitter from "@/event-bus";
                 ^
    9 | 
   10 | 
   11 | const actions: ActionTree<OrderState, RootState> = {
   
   
warning: 'state' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/order/actions.ts:51:25:
   49 |     commit(types.ORDER_CURRENT_UPDATED, state.current )
   50 | },
 > 51 |   async addOrderItem ({ state, commit }, payload) {
      |                           ^
   52 |     const product = { 
   53 |       ...payload,
   54 |       quantityAccepted: 0,
   
   
 warning: 'commit' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/order/actions.ts:109:34:
  107 |     return resp;
  108 |   },
> 109 |   async createPurchaseShipment({ commit }, payload) {
      |                                    ^
  110 | 
  111 |     let resp;
  112 |     try {
  
  
warning: 'commit' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/product/actions.ts:65:36:
   63 |     return resp;
   64 |   },
 > 65 |   async fetchProductInformation( { commit }, payload) {
      |                                      ^
   66 |     let productIds: any = new Set();
   67 | 
   68 |     payload.order.map((item: any) => {
   
   
 warning: 'commit' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/shipment/actions.ts:65:26:
   63 |     }
   64 |   },
 > 65 |   receiveShipmentItem ({ commit }, data) {
      |                            ^
   66 |     const payload = data.shipment ? {
   67 |       shipmentId: data.shipment.shipmentId,
   68 |       locationSeqId: data.shipment.locationSeqId
   
5 warnings found.
   ```

**Comment by adityasharma7** [comment]
@k2maan 
Check if build warnings still exist
